services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: always
